//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_CarSells_Project_3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    
    public partial class Table
    {
        public int Id { get; set; }
        [Required]
        public string Car_Name { get; set; }
        [Required]
        public string Owner { get; set; }
        [Required]
        public decimal Phone_Number { get; set; }
        [Required]
        public decimal Price { get; set; }
        [Required]
        public string Payment_Method { get; set; }
        [Required]
        public string Transmission { get; set; }
        [Required]
        public string Condition { get; set; }
        public bool Licensed { get; set; }
        public string CarImgPath { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
